# tmux
set-option -g status-position top
set-option -g status-style "bg=default,fg=#f0f0f0"
set-option -g status-justify centre
set -g window-status-current-format "#{pane_current_path}"
set-environment -g HYPRLAND_INSTANCE_SIGNATURE "$HYPRLAND_INSTANCE_SIGNATURE"
set-option -g update-environment "$HYPRLAND_INSTANCE_SIGNATURE"
set-option -g mode-keys vi

# status line
set -g status-right-length 100
set -g status-left "#(~/.files/scripts/tmux-workspaces)"
set -g status-right  "#(~/.files/scripts/tmux-ifstat)|bl#(cat /sys/class/backlight/intel_backlight/brightness)|vol#(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2 * 100)}')%|cpu#(~/.files/scripts/cpu)|t#(awk '{print $1 / 1000}' /sys/class/thermal/thermal_zone0/temp)°C|mem#(~/.files/scripts/memory)|bat#(cat /sys/class/power_supply/BAT1/capacity)%|%b%d|%H:%M"
set-option -g status-interval 5

# binds
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# use mouse
set -g mouse on
