#!/bin/bash

wallpaper=$(hyprctl hyprpaper listactive | awk "NR==1 {print $1}" | sed 's/.*\///')

if [ $wallpaper == "brushy-peak-regional-preserve-1600-900.jpg" ]; then
  hyprctl hyprpaper wallpaper "eDP-1, $HOME/.files/wallpapers/jupiter-1600-900.jpg"
elif [ $wallpaper == "jupiter-1600-900.jpg" ]; then
  hyprctl hyprpaper wallpaper "eDP-1, $HOME/.files/wallpapers/brushy-peak-regional-preserve-1600-900.jpg"
fi
