#!/bin/bash

time_const=$(ifstat wlp3s0 | awk 'NR==1 {print $3}' | sed 's/.*\(.\)$/\1/')

if [ "$time_const" == "5" ]; then
  echo -n "$(ifstat --interval=5 wlp3s0 | awk 'NR==4 {print $7}')/"; echo "$(ifstat --interval=5 wlp3s0 | awk 'NR==4 {print $9}')"
else
  ifstat --scan=5 --interval=5
fi
